### ISSUE TITLE
DSBulk 1.6.0 count output misses duration information

### ISSUE THREAD

**Issue by msmygit** [datastax/dsbulk#369]
When performing a count operation, the duration information is missing from the output. See the below example at this line the duration info is missing `Operation COUNT_20200721-152032-786471 completed successfully in .`,

```
$ ./dsbulk count -k test1 -t table1 -h 12.121.22.96 -u cassandra -p REDACTED --stats.mode partitions --stats.numPartitions 15
Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
Operation directory: /path/to/dsbulk-1.6.0/bin/logs/COUNT_20200721-152032-786471
total | failed | rows/s | p50ms | p99ms | p999ms
  100 |      0 |     82 | 77.10 | 94.90 |  94.90
Operation COUNT_20200721-152032-786471 completed successfully in .
100
```

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-11) by [Unito](https://www.unito.io)

**Comment by adutra** [comment]
DSBulk 1.6.1 will print: `completed successfully in less than one second.`
