### ISSUE TITLE
honor metadata while performing unload and load

### ISSUE THREAD

**Issue by jaibheem** [datastax/dsbulk#377]
Hello, 

I am trying to import the data from one Cassandra cluster to another, however I see the ttl and writetime metadata is not honored. Can we enhance the utility to honor the TTL and Write time values?

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-9) by [Unito](https://www.unito.io)

**Comment by adutra** [comment]
Hi, preserving TTL and writetime when migrating data from one cluster to another is possible, but requires several steps. Check out [this blog post](https://www.datastax.com/blog/2019/12/datastax-bulk-loader-examples-loading-other-locations), and follow example 30.1.

We have an internal TODO to make this more streamlined for users, but for now, you'll have to go with the procedure described in the post.

**Comment by adutra** [comment]
@jaibheem is it working for you now? Can we close this?

**Comment by jaibheem** [comment]
yes, thank you
