### ISSUE TITLE
DSBulk interprets newline characters `\n` in text columns and writes multiple lines per record to output file

### ISSUE THREAD

**Issue by BrandonBordeaux** [datastax/dsbulk#378]
When unloading text columns from Cassandra that contain newline character `\n`, the newline will be interpreted and DSBulk will write the row to the output file (CSV) over multiple lines. This is not the desired behavior; it is expected that these newline characters are written out as part of the text column data and the row is contained to a single line in the output file.

For example:

Text Column = `First line.\nSecond line.`

Current DSBulk Unload to CSV behavior:

```
First line.
Second line.
```

Desired behavior:

```
First line.\nSecond line.
```

**NOTE:** In order to reproduce this behavior, insert test data using the Datastax Java Driver for Apache Cassandra; also tested with Python driver. CQLSH will escape the newline character `\\n`, so rows inserted with CQLSH does not produce this issue.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-8) by [Unito](https://www.unito.io)

**Comment by msmygit** [comment]
Here is the testing that I did for this ticket.

### Table Definition
```
CREATE TABLE test.dsbulk (
    pk int PRIMARY KEY,
    c1 text
);
```
### Input CSV file contents. Notice 1st one is quoted and 2nd one isn't
```
$ cat dsbulk.csv
pk,c1
1,'First line.\nSecond line.'
2,First line.\nSecond line.
```

### DSBulk version
```
$ ./dsbulk --version
DataStax Bulk Loader v1.7.0
```
### DSBulk execution command and output
```
$ ./dsbulk load -k test -t dsbulk -header true -url ./dsbulk.csv 
Operation directory: /Users/madhavan.sridharan/Data/Tools/DSBulk/dsbulk-1.7.0/bin/logs/LOAD_20201014-143653-997467
total | failed | rows/s | p50ms | p99ms | p999ms | batches
    2 |      0 |      7 |  5.89 |  8.59 |   8.59 |    1.00
Operation LOAD_20201014-143653-997467 completed successfully in less than one second.
Last processed positions can be found in positions.txt
```
### Result from CQLSH
```
cqlsh:test> select * from test.dsbulk ;

 pk | c1
----+-----------------------------
  1 | 'First line.\nSecond line.'
  2 |   First line.\nSecond line.

(2 rows)
```
### DSBulk unload operation activity
```
$ ./dsbulk unload -k test -t dsbulk -header true -url ./dsbulk_unload
Operation directory: /Users/madhavan.sridharan/Data/Tools/DSBulk/dsbulk-1.7.0/bin/logs/UNLOAD_20201014-144238-583471
total | failed | rows/s | p50ms | p99ms | p999ms
    2 |      0 |      4 |  7.62 | 12.98 |  12.98
Operation UNLOAD_20201014-144238-583471 completed successfully in less than one second.
```
### Output of the unloaded csv files
```
$ ls dsbulk_unload/output-00000
output-000001.csv  output-000002.csv

$ cat dsbulk_unload/output-00000*.csv
pk,c1
2,First line.\nSecond line.
pk,c1
1,'First line.\nSecond line.'
```

### Java Program using Java Driver 4.9.0
I tried to insert records with DataStax Java Driver `4.9.0` using the below code and still couldn't repro this behavior,
```
import java.net.InetSocketAddress;

import com.datastax.oss.driver.api.core.CqlSession;
import com.datastax.oss.driver.api.core.cql.ResultSet;

public class DAT617 {
    public static void main(String... args) {
	try (CqlSession session = CqlSession.builder().addContactPoint(new InetSocketAddress("localhost", 9042))
		.withLocalDatacenter("dc1").build()) { // Change values to match your environment
	    ResultSet rs = session.execute("insert into test.dsbulk(pk,c1) values (3,'First line.\\nSecond line.')");
	}
    }
}
```
### CQLSH output of the 3rd record inserted into the test table
```
cqlsh:test> select * from test.dsbulk ;

 pk | c1
----+-----------------------------
  1 | 'First line.\nSecond line.'
  2 |   First line.\nSecond line.
  3 |   First line.\nSecond line.

(3 rows)
```
### DSBulk unload command run and the output csv file contents
```
$ ./dsbulk unload -k test -t dsbulk -header true -url ./dsbulk_unload
Operation directory: /Users/madhavan.sridharan/Data/Tools/DSBulk/dsbulk-1.7.0/bin/logs/UNLOAD_20201014-150212-234300
total | failed | rows/s | p50ms | p99ms | p999ms
    3 |      0 |      9 |  1.41 |  1.49 |   1.49
Operation UNLOAD_20201014-150212-234300 completed successfully in less than one second.
```
and the output of the unloaded csv files are below,
```
$ cat dsbulk_unload/output-00000*.csv
pk,c1
1,'First line.\nSecond line.'
pk,c1
3,First line.\nSecond line.
pk,c1
2,First line.\nSecond line.
```
FWIW, I tested this against `DSE 6.7.10`. I don't _think_ DSBulk is doing it wrong in here. Do we've a full minimal reproducible example to reproduce this behavior?

**Comment by adutra** [comment]
This has been discussed internally and it appears there was just some misunderstanding about how newline characters are processed by CQLSH and DSBulk. All is good now.

**Comment by ibeatmybrothers** [comment]
Hi @adutra I see this issue still present in version 1.7 and 1.8 running against a 5.1.14 cluster. Cqlsh COPY TO command will copy the exact contents, but the dsbulk unload command will interpret or omit escaped characters, such as \0xf and \r\n when present in a text column.

**Comment by adutra** [comment]
Hi @ibeatmybrothers do you have a reproducer? Because we discussed this internally and I wasn't able to see any defect in how DSBulk exports such characters. Thanks!

(Note: the example reported above by @msmygit did not contain actual line breaks, but only escaped `\n` sequences. These are not converted by DSBulk in any way)
