### ISSUE TITLE
DSBulk load fails when the primary key column is empty

### ISSUE THREAD

**Issue by jaibheem** [datastax/dsbulk#382]
Hello Team,

I am trying to load a data file into the Cassandra cluster and running into error if the one of the Primary key column is empty. Is there any option/way to safely insert these entries? I read the documentation that it's not possible but can we somehow fill these values to a null value during the Unload operation itself, so the load can happen?

```
--schema.allowMissingFields
--dsbulk.schema.allowMissingFields <boolean>
Specify whether or not to accept records that are missing fields declared in the mapping. For example, if the mapping declares three fields A, B, and C, but a record contains only fields A and B, then if this option is true, C will be silently assigned null and the record will be considered valid, and if false, the record will be rejected. If the missing field is mapped to a primary key column, the record will always be rejected, since the database will reject the record. This setting also applies to user-defined types and tuples. Only applicable for loading, ignored otherwise.

This setting is ignored when counting.

Default: false.


```

I can easily achieve this with the CQLSH utility

```
COPY keyspace.table to '/tmp/table.txt' WITH NULL = 'null'; --> export
COPY newkeyspace.table FROM '/tmp/table.txt' WITH NULL = 'null'; --> import
```

I am using 1.7.0 version of DSBulk and below is the sample data format

```
id,scope,name,tags,created_by,ver
abc123de,"",key,"{\"key\":\"value\"}",,b7258e80-5518-11eb-b06e-7d24a9bd009c
```

Primary Key: (id, scope)

Please let me know if you need more information.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-6) by [Unito](https://www.unito.io)

**Comment by adutra** [comment]
Hi, have you tried `dsbulk.codec.nullStrings` ?

https://docs.datastax.com/en/dsbulk/doc/dsbulk/reference/codecOptions.html#codecOptions__dsbulkCodecOptionsNullStrings

**Comment by jaibheem** [comment]
yes I tried that  but it did not help and I believe this is the correct syntax? `--dsbulk.codec.nullStrings scope` where scope is my primary key column name.

**Comment by adutra** [comment]
No that's not how it works :-)

The argument you pass is the value that will be printed out for _every_ null column in the result set. E.g. `--dsbulk.codec.nullStrings THIS_COLUMN_WAS_NULL` would produce something like:

```
id,scope,name,tags,created_by,ver
abc123de,THIS_COLUMN_WAS_NULL,key,"{\"key\":\"value\"}",,b7258e80-5518-11eb-b06e-7d24a9bd009c
```

Let me know if that helps!

**Comment by adutra** [comment]
Hi @jaibheem can we close this one?
