### ISSUE TITLE
Split timestamp into date and hour 

### ISSUE THREAD

**Issue by graziella79** [datastax/dsbulk#386]
Hello,
I need to load into cassandra a csv file with a date string yyyyMMddHHmmss and I need to split this string into two separate columns: 
1)datetest : yyyyMMddHHmmss
2)partition_id : yyyyMMddHH
Example:
(input csv) 
aaaa|bbbb|20210531041034

(table cassandra)
table test(A text, B text,  datetest text, partition_id text) 
--->('aaaa','bbbb,20210531041034,2021053104)

Is it possible with dsbulk?
Thanks 
Graziella

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-3) by [Unito](https://www.unito.io)

**Comment by adutra** [comment]
Hi @graziella79 unfortunately that's not possible :-( 

While it is possible to store one CSV field in two columns, this will only work if the two columns have the same pattern. 

If you need different patterns, you will have to transform your CSV file first, then load it with dsbulk.

I think you could transform you file very easily with sed for example:

```
 sed -E 's/(.*\|)([0-9]{10})([0-9]{4})/\1\2\3|\2/g' file.csv
```

**Comment by adutra** [comment]
@graziella79 are you OK to close this one?

**Comment by graziella79** [comment]
Thank you so much for your answer!
