### ISSUE TITLE
Can't find auth-provider class

### ISSUE THREAD

**Issue by feedhandler** [datastax/dsbulk#388]
Hi, 
I'm trying to use advanced.auth-provider.class=software.aws.mcs.auth.SigV4AuthProvider but dsbulk can't seem to find the class. It fails with error

```
Can't find class software.aws.mcs.auth.SigV4AuthProvider (specified by advanced.auth-provider.class).
```

I've tried putting the jar file in a variety of locations (lib dir, conf dir, etc) but it didn't help
Any idea how to fix this?
Thanks

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-13) by [Unito](https://www.unito.io)

**Comment by feedhandler** [comment]
Thanks, I already tried that but it didn't work. How do I turn this ticket into a Bug? I don't see any options to do that...

**Comment by adutra** [comment]
Hi @feedhandler I finally had some time to investigate this.

The problem is that adding the jar `aws-sigv4-auth-cassandra-java-driver-plugin-4.0.6.jar` only is not enough. It has a bunch of dependencies and you need to add them as well:

```
[INFO] +- software.aws.mcs:aws-sigv4-auth-cassandra-java-driver-plugin:jar:4.0.6:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  +- javax.validation:validation-api:jar:2.0.0.Final:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.13.1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.13.1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.1:compile
[INFO] |  \- software.amazon.awssdk:auth:jar:2.15.66:compile
[INFO] |     +- software.amazon.awssdk:annotations:jar:2.15.66:compile
[INFO] |     +- software.amazon.awssdk:utils:jar:2.15.66:compile
[INFO] |     +- software.amazon.awssdk:sdk-core:jar:2.15.66:compile
[INFO] |     |  \- software.amazon.awssdk:metrics-spi:jar:2.15.66:compile
[INFO] |     +- software.amazon.awssdk:regions:jar:2.15.66:compile
[INFO] |     +- software.amazon.awssdk:profiles:jar:2.15.66:compile
[INFO] |     +- software.amazon.awssdk:http-client-spi:jar:2.15.66:compile
[INFO] |     \- software.amazon.eventstream:eventstream:jar:1.0.1:compile
```

Let me know if this helps!

**Comment by feedhandler** [comment]
Thanks for looking into it. Unfortunately I'm no longer working with cassandra so I won't be able to try this.
