### ISSUE TITLE
Count does not print any results after 2 hours, 2 failures, 6.5B rows. 

### ISSUE THREAD

**Issue by smatvienko-tb** [datastax/dsbulk#394]
Hi!
I faced an issue that COUNT does not print any results after 2 hours, 2 failures, 6.5 billion rows. 
Here is my PR as a proposal how to fix this issue https://github.com/datastax/dsbulk/pull/393
![image](https://user-images.githubusercontent.com/79898499/140290765-a18db6a2-7f7e-4937-a7c7-9934fa0444f4.png)
Thank you!

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-18) by [Unito](https://www.unito.io)

**Comment by adutra** [comment]
Fixed by #393.
