### ISSUE TITLE
Add support for nested function in mappings

### ISSUE THREAD

**Issue by adutra** [datastax/dsbulk#412]
Currently the following is disallowed by the mapping grammar:

```
toTimestamp(now())=fieldA
```

Indeed the grammar rule for function arguments is:

```
functionArg
    : columnName
    | literal
    ;
```

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-29) by [Unito](https://www.unito.io)

**Comment by msmygit** [comment]
Here is my example:
```
% ./dsbulk --version
DataStax Bulk Loader v1.8.0
```

I've a very simple table 

`CREATE TABLE db3.dsbulk ( a int PRIMARY KEY, b date);`  in AstraDB.

When I try to run the following:

`./dsbulk load -k db3 -t dsbulk -url dsblk.csv -header false -m "0 = a, CurrentDate() = b" -u ABC -p ZYZ -b SCB.zip` I get an error of `Operation LOAD_20220401-101417-525034 failed: Unknown function CurrentDate called`

My input csv just this:
```
cat dsblk.csv
a
1
```

Why is `CurrentDate()` not accepted? I also tried the `currentDate()` camelCase flavor as well but no luck. `currentDate()` does appears to be a valid native function in AstraDB - [docs.datastax.com/en/astra-cql/doc/cql/cql_reference/…](https://docs.datastax.com/en/astra-cql/doc/cql/cql_reference/refCqlFunction.html#refCqlFunction__currentDate)

**Comment by adutra** [comment]
> Why is CurrentDate() not accepted? I also tried the currentDate() camelCase flavor as well but no luck.

Try `currentdate()`: function names in DSBulk mappings are supposed to be in internal form, and I suspect the internal form for this function is simply `currentdate`.

**Comment by adutra** [comment]
Confirmed:

```
cqlsh> select currentdate() from system.local;

 system.currentdate()
----------------------
           2022-04-01

(1 rows)
```

**Comment by msmygit** [comment]
Using `currentdate()` form worked. Thank you @adutra ! 👍🏼

**Comment by msmygit** [comment]
Curious, where in the code one could see all the DSBulk internal forms for native functions?

In Astra DB CQL Console:
```
token@cqlsh> SELECT CurrentDate() FROM system.local;

 system.currentdate()
----------------------
           2022-04-01

(1 rows)
```

**Comment by adutra** [comment]
Re: function names in Cassandra, most (all?) built-in functions are actually fully lowercase in internal form. Because CQL forms are case-insensitive, the function `currentdate` can be written `currentDate` or `CurrentDate` or even `CuRrEnTdAtE` – all of these names are reduced to `currentdate`. The docs usually chose a camel-case CQL form for a better readability. 

However DSBulk mapping syntax is different. Function names MUST appear in internal form. So only `currentdate` can work, all other forms will not work.
