### ISSUE TITLE
Can't unload keyspace dse_audit

### ISSUE THREAD

**Issue by nhtha** [datastax/dsbulk#418]
dsbulk may have bugs, I received error "Operation UNLOAD_20220419-073654-099023 failed: Keyspace dse_audit does not exist." when I tried to unload table dse_audit.audit_log. Using cqlsh or another cassandra client tool, I can query this table normaly.
Please take a look and fix this.
Many thanks,
Ha Nguyen

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-32) by [Unito](https://www.unito.io)

**Comment by adutra** [comment]
Hi @nhtha this is because by default the driver does not load metadata for DSE keyspaces.

You can change that by setting the following option :

```sh
dsbulk unload -k dse_audit -t audit_log --driver.advanced.metadata.schema.refreshed-keyspaces dse_audit -h ...
```

**Comment by nhtha** [comment]
> Hi @nhtha this is because by default the driver does not load metadata for DSE keyspaces.
> 
> You can change that by setting the following option :
> 
> ```shell
> dsbulk unload -k dse_audit -t audit_log --driver.advanced.metadata.schema.refreshed-keyspaces dse_audit -h ...
> ```

Thank you, it's works.

**Comment by adutra** [comment]
Glad to hear that! Closing then.
