### ISSUE TITLE
DSBulk's option for "ansiMode" doesn't work

### ISSUE THREAD

**Issue by jnorcross** [datastax/dsbulk#419]
Tried to utilize the ansiMode options as documented here: https://github.com/datastax/dsbulk/blob/d9107caf9a4a286c06d8e8f089e18d4e798993a2/manual/settings.md#log 
--dsbulk.log.ansiMode
--log.ansiMode

However, neither option appears to have any effect on the color scheme that is given as output.

Test #1 running dsbulk in a windows command:
![image](https://user-images.githubusercontent.com/52834283/168081682-6bd6e1de-4f70-463f-b23d-55f25e04fab9.png)

In the image above, we can see that the ansiMode is set to disable, but still we are getting colors in the output.

We have a second test where we are using dsbulk through our application written in C#, when we apply the "force" option we still do not receive any ANSI colors in our logged output.  This is making debugging the problem with ANSI colors appearing in some environments but not other environments hard to debug as we cannot control the color scheme when invoking dsbulk commands.  Ultimately we would like to use the 'disable' option to turn off ANSI colors completely so that we don't have to strip the colors in our logic when parsing the numbers from the log.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-33) by [Unito](https://www.unito.io)

**Comment by jnorcross** [comment]
Looking through the code.  The option appears to be 'disabled' not 'disable'.  It also appears that only '--log.ansiMode' is supported and '--dsbulk.log.ansiMode' is not.  So maybe the documentation is wrong and needs to be updated?  'force' option was still not generating ANSI colors though when using a redirected stream through a windows command process invoked with C#.

**Comment by adutra** [comment]
Hi @jnorcross thanks for reporting this. 

1. The right value is `disabled` indeed, not `disable` – this is a typo in the docs and I will get it fixed asap.
2. You are right, `--dsbulk.log.ansiMode` has never been supported – this is a bug and I will also fix it soon.

> 'force' option was still not generating ANSI colors though when using a redirected stream through a windows command process invoked with C#.

I am not sure how I can help here (I'm not familiar with Windows or C# at all) but I'll investigate.
