### ISSUE TITLE
Upgrade esri-geometry-api to 2.x to get rid of JSON 20090211 and SONATYPE-2022-3061

### ISSUE THREAD

**Issue by nicoloboschi** [datastax/dsbulk#422]
Sonatype scan says that the codecs-api project is using 1.21 which contains `org.json:json:20090211` which has a critical vulnerability.
Starting from 2.0 esri-geometry-api doesn't carry the JSON dependency anymore. 
https://github.com/Esri/geometry-api-java/releases/tag/v2.0.0

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-35) by [Unito](https://www.unito.io)

**Comment by nicoloboschi** [comment]
@adutra PTAL, this is needed to make a couple of Streaming projects pass the Sonatype Security Scan

**Comment by adutra** [comment]
@nicoloboschi I we can't use ESRI 2. DSE itself is still using ESRI 1 and so upgrading any client to ESRI 2 would be not only complex, but would probably break everything related to geotypes.

I can, however, upgrade `org.json`. In fact I was exactly crafting a PR for that. I will open it today.

**Comment by adutra** [comment]
BTW if you don't need geotypes in your project, you can just get rid of ESRI and its transitive dependencies. DSBulk and the driver can live without them.

**Comment by nicoloboschi** [comment]
We're still using dsbulk 1.6.0. We use it for cql conversion types. Do you think it'd safe to only upgrade JSON to `20220320` keeping dsbulk-codecs to 1.6.0 ?

**Comment by adutra** [comment]
Yes you can do the json upgrade in your project. This should be enough to get rid of the security alerts.
