### ISSUE TITLE
Auto-detect and accommodate AstraDB server-side rate-limit situation

### ISSUE THREAD

**Issue by weideng1** [datastax/dsbulk#435]
We need a way for dsbulk to auto-detect if the remote end is AstraDB, and if it is, apply a default ingestion rate that's more inline with the remote end's capacity.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-42) by [Unito](https://www.unito.io)

**Comment by adutra** [comment]
For the record, when the limit is reached DSBulk stops with too many errors:

```
Operation LOAD_20220728-152323-700017 aborted: Too many errors, the maximum allowed is 100.
```

In load-errors.log we typically find a `BulkExecutionException` wrapping an `AllNodesFailedException` containing this kind of error:

```
com.datastax.oss.driver.api.core.servererrors.OverloadedException: Node(...) is overloaded: Rate limit reached, please consult our documentation at https://astra.dev/rate-limit
```
